### ISSUE TITLE
BDP/BDH

### ISSUE THREAD

**Issue by flaviodrt** [alex314159/blpapiwrapper#10]
Hi Alex, how are you?
Have you heard about Bloomberg deactivating BDP and BDH functions?
Thank you!

**Comment by alex314159** [comment]
I haven’t! Where do you see that? Is that only for Excel or all the APIs? 

Thanks

**Comment by flaviodrt** [comment]
I don't know yet.
I'm going to have a meeting tomorrow with Bloomberg. 
I've decided to create this thread in case of you had some information.
I hope to have some news tomorrow.

**Comment by flaviodrt** [comment]
They aren't going to disable BDP and BDH functions. Someone has given me the wrong information.
Today they presented to me the BQL (Bloomberg Query Language), it's a new Excel function, that I don't know if it avaible for all APIs, and it's more verbose and more flexible. They also talked about a new feature that is in beta testing that allow to code Python inside Jupyter Notebook on Bloomberg Terminal software.

**Comment by flaviodrt** [comment]
This new feature is called Bquant

**Comment by alex314159** [comment]
Thank you Flavio. I’ve seen a preview of it - looks very promising especially to share work between users.
