### ISSUE TITLE
 'MessageIterator' object has no attribute 'next'

### ISSUE THREAD

**Issue by sharsid** [alex314159/blpapiwrapper#16]
have you experienced this issue?

error with US900123AL40 Govt PX_LAST
nan

error with US900123AL40 Govt YLD_YTM_BID
nan

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-3cd85cb55d27> in <module>
----> 1 excelEmulationExample()

S:\Python\scripts\blpwrap.py in excelEmulationExample()
    527     print(bloomberg.bdp('US900123AL40 Govt', 'YLD_YTM_BID', 'PX_BID', '200'))
    528     print('')
--> 529     print(bloomberg.bdh())
    530     print('')
    531     print(bloomberg.bdhOHLC())

S:\Python\scripts\blpwrap.py in bdh(self, strSecurity, strData, startdate, enddate, adjustmentSplit, periodicity, strOverrideField, strOverrideValue)
    131                 break
    132 
--> 133         fieldDataArray = blpapi.event.MessageIterator(event).next().getElement(SECURITY_DATA).getElement(FIELD_DATA)
    134         fieldDataList = [fieldDataArray.getValueAsElement(i) for i in range(0, fieldDataArray.numValues())]
    135         outDates = [x.getElementAsDatetime(DATE) for x in fieldDataList]

AttributeError: 'MessageIterator' object has no attribute 'next'

**Comment by alex314159** [comment]
Are you connected to bbg on the terminal? Is it the only example call that's failing?

**Comment by V-kik** [comment]
I had the same issue.
In the latest blpapi.event, the MessageIterator only has a private function __next__(). I used this one in alex's wrapper and its working now.

**Comment by sharsid** [comment]
@V-kik  how did you fix the issue?

**Comment by alex314159** [comment]
which version of blpapi are you using? all works fine for me with 3.15.2, try `blpapi.version()`. Happy to incorporate fix of course can you show what you replaced code with? thanks,

**Comment by sharsid** [comment]
I'm on blpapi 3.18.2
