### ISSUE TITLE
Dividends

### ISSUE THREAD

**Issue by jonathanng** [alex314159/blpapiwrapper#3]
I think this is related to a previously closed issue.

How do you get historical dividends?

By the way, this is clearly the best Bloomberg lib for Python out there. Good job!

**Comment by alex314159** [comment]
Thanks. I'm not sure this is possible unfortunately. Looking at the Excel API it seems to use a different function to look up that data (=BDS("AAPL US Equity","DVD_HIST_ALL") for example). I'm not sure how to emulate the BDS function, it doesn't seem to be described in the API developer's guide. I'm seeing the Bloomberg API guys in the next few days though and will ask them.

**Comment by jonathanng** [comment]
I found a way!

https://github.com/alex314159/blpapiwrapper/pull/4
