### ISSUE TITLE
Bug in BDH function

### ISSUE THREAD

**Issue by ak395341** [alex314159/blpapiwrapper#5]
Hi Alex. I think this is a bug with the way your code handles fields that start on different days. 

The following fails:
dummy_bberg_query = bbg.BLP.bdh(bbg.BLP(), strSecurity='USGG2YR Index', strData = ['PX_LAST', 'PX_OPEN'], startdate = datetime.datetime(1985,1,1), enddate = datetime.datetime.now(), periodicity = 'MONTHLY')

dummy_bberg_query = bbg.BLP.bdhOHLC(bbg.BLP(), strSecurity='USGG2YR Index', startdate = datetime.datetime(1985,1,1),  enddate = datetime.datetime.now(), periodicity = 'MONTHLY')

but the following runs totally fine:
dummy_bberg_query = bbg.BLP.bdh(bbg.BLP(), strSecurity='USGG10YR Index', strData = ['PX_LAST', 'PX_OPEN'], startdate = datetime.datetime(1985,1,1), enddate = datetime.datetime.now(), periodicity = 'MONTHLY')

the following also works:
dummy_bberg_query = bbg.BLP.bdh(bbg.BLP(), strSecurity='USGG2YR Index', strData = 'PX_LAST', startdate = datetime.datetime(1985,1,1), enddate = datetime.datetime.now(), periodicity = 'MONTHLY')

dummy_bberg_query = bbg.BLP.bdh(bbg.BLP(), strSecurity='USGG2YR Index', strData = 'PX_OPEN', startdate = datetime.datetime(1985,1,1), enddate = datetime.datetime.now(), periodicity = 'MONTHLY')

I think the issue is that your BDH implementation fails on multiple fields when the returned histories are of different lengths. Individual queries for those fields work fine and I can join them myself. Let me know...thx.

**Comment by alex314159** [comment]
hi,

You nailed it, I’m implicitly making the assumption that the history for different fields are of similar length (which is usually but not always the case). At the moment best is to join yourself. Alternatively I could probably do one pass to check the longest data, then fill sequentially with pandas.np.nan if no data is available.

**Comment by ak395341** [comment]
No worries. Appreciate you making this available and wanted to point out an issue I caught. Let me know if this ever changes as it makes the implementation slightly faster/cleaner on my side. 

Thx,
Aaron

**Comment by alex314159** [comment]
Just committed a change, try the SimpleHistoryRequest function - it should do what you want. If you're doing anything other than scripting I would highly recommend against using the BLP class (in favor of BLPTS).
