### ISSUE TITLE
intro + print

### ISSUE THREAD

**Issue by jaredpohl** [alex314159/blpapiwrapper#7]
new to python...

could you give a couple of examples on how to run the wrapper...?

also, was getting an error on print method, i've added ()'s.. im using python 3x...

**Comment by alex314159** [comment]
There are some examples in the code already, towards the end - what are you trying to achieve?

**Comment by jaredpohl** [comment]
I've installed it in my path
Python blpapiarappwer.py install

Then imported blpapiwrapper as bbrg

Just want connect to Bloomberg, collect px_last historically for a security
and return it as a datatframe

**Comment by alex314159** [comment]
Just go in the folder where the file is and do python -i blpapiwrapper.py 

Then you can run through the examples in the code.

**Comment by jaredpohl** [comment]
ok great thanks - how would i include this code in a jupiter notebook??

**Comment by alex314159** [comment]
Sorry but for general Python help you're better off trying stackoverflow or ideally someone on your desk.
