### ISSUE TITLE
Stream

### ISSUE THREAD

**Issue by Fux002** [alex314159/blpapiwrapper#8]
Can i please get an example to start and stop 2 distinct streams on to get SPX Index data and the other one to get MSFT US EQUITY data.
Thank you very much. I cant get my head around starting a stream and stopping one properly.

Fons

**Comment by alex314159** [comment]
Something like:
    stream = BLPStream('SPX Index', ['PX_LAST']], 0, 1)
    obs = ObserverStreamExample()
    stream.register(obs)
    stream.start()
    #At that point stream.output should always have the last price. Anytime a new price comes the obs will print it to the console (as defined in the ObserverStreamExample)
    stream.closeSubscription() #when you no longer need updates

And you can repeat for the MSFT US Equity with e.g. stream2 and obs2.

There is a much more elaborate use in my bondpricer repository, in the bonddatamodel file (it might not run as it needs config files, but you'll get an idea of what's possible in practice and how to use observers).

**Comment by alex314159** [comment]
I just realised the above doesn't work. What seems to happen is that not all fields are "streamable". So     `stream = BLPStream('ESH7 Index', ['PX_LAST'], 0, 1)`
doesn't work but
`stream = BLPStream('ESH7 Index', ['BID'], 0, 1)`
does. I suggest you go on the terminal, select your security, and do FLDS<GO> to get a list of fields and then try and error until you find one that's streamable.

**Comment by Fux002** [comment]
Hey yea you need a live field LAST_PRICE works.


Thx a lot!!!

**Comment by Fux002** [comment]
Hwy Alex,

One more thing.

if I called the treamPatternExample() and the stream is funning. How do a
call the STOP stream function if I list the stream object in the mean
while. is there a way to fetch all the active stream objects. I suppose
they get destroyed once the script is closed?

**Comment by alex314159** [comment]
Not sure exactly... you stop stream with stream.closeSubscription(). I am streaming ~900 securities in a live environment and performance is OK, so I wouldn't necessarily close a stream. Maybe you can start a big stream with all the securities you need, and then add one observer per security you care, and then you can list all the observers and add or remove observers at will.

**Comment by Fux002** [comment]
Ok just so it's clear. Passes the run time of my script. On the Bloomberg side the stream is active. On my script side the stream objets is gone as the script terminated.  How can I find that stream back in another

**Comment by alex314159** [comment]
Can you post an example? I guess you don't want your script to ever terminate, ideally you start a separate thread. Not exactly sure what you need

**Comment by Fux002** [comment]
Hey Alex, thank you for your kind replays much obliged.

I leave a list of tickets that constantly changes. Every 10 minutes for example. I want to set up a stream that understands that the list can change, it should connect to a server and get the new list for example with some simple SQL Select and update the stream for this new list.

How is this best done making sure I close of old streams of tickets no longer relevant and make sure the new tickets are added to the stream. 

It doesn't have to be insane quick just within reason.

Is what I need understandable.

Thx a lot!

Fons

**Comment by alex314159** [comment]
I think it's possible to add and delete securities from a subscription request but you would need to change the source code of my implementation. Without doing so, what I would do is the following:

Create an observer O that fits your final usage (be it display on screen, save in a database, etc). That object will never die.

Open a stream S1 with your initial tickets, add O as an observer. Start S1. Once you need a new list every 10 minutes you can kill S1 and create S2 with the new tickers, add the same O as observer, start S2 and so forth.

Hope this helps,

**Comment by Fux002** [comment]
Sounds pretty good :)

That will do!

Thx a lot.

Have a great eve and speak soon.

You are in London right?

**Comment by alex314159** [comment]
Yes

**Comment by Fux002** [comment]
Catch you on Bloomberg perhaps.

Fons vermorken Altana Awealth.
